name: Test Two Municipalities

on:
  # Allow manual trigger only
  workflow_dispatch:

jobs:
  test-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate test data (Zwolle and Elburg only)
        run: python test_two_municipalities.py
        working-directory: ${{ github.workspace }}

      - name: List generated files
        run: |
          echo "📁 Files in webapp/public/data:"
          ls -lh webapp/public/data/zwolle* webapp/public/data/elburg* || echo "Files not found"

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Commit and push if changed
        run: |
          git add webapp/public/data/zwolle.geojson webapp/public/data/zwolle.geojson.gz
          git add webapp/public/data/elburg.geojson webapp/public/data/elburg.geojson.gz
          git diff --quiet && git diff --staged --quiet || (git commit -m "🧪 Test update for Zwolle and Elburg - $(date +'%Y-%m-%d %H:%M UTC')" && git push)
